name: stream_deck_sdk
description: A Dart package for building Elgato Stream Deck plugins.
version: 0.0.1
repository: https://github.com/DanTup/streamdeck.dart

environment:
    sdk: '>=2.18.0 <3.0.0'
