name: stream_deck_sdk
description: A package for building Elgato Stream Deck plugins in Dart for macOS and Windows.
version: 1.0.1
repository: https://github.com/ChekTek/streamdeck_dart_sdk
issue_tracker: https://github.com/ChekTek/streamdeck_dart_sdk/issues

environment:
    sdk: '>=2.18.0 <3.0.0'

platforms:
    macos:
    windows:
